example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = young_adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = young_adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = young_adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = young_adult, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = senior, gender = female, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = senior, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = young_adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(has_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(has_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(has_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = young_adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = senior, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = young_adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = senior, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = high, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = normal, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = male, resting_bp = low, cholesterol_level = high, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = female, resting_bp = high, cholesterol_level = normal, blood_sugar = high, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = hard]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = easy]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = middle_age, gender = male, resting_bp = low, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = senior, gender = male, resting_bp = high, cholesterol_level = low, blood_sugar = high, cp_only_exercise = no, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = male, resting_bp = normal, cholesterol_level = low, blood_sugar = low, cp_only_exercise = yes, max_exer_difficulty = medium]).
example(no_risk, [age_category = adult, gender = female, resting_bp = normal, cholesterol_level = normal, blood_sugar = low, cp_only_exercise = no, max_exer_difficulty = medium]).
